name: ci-docs

on:
- pull_request

jobs:
  docs-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs/
