name: ci-scripts

on: [pull_request, push]

jobs:
  macos-intallers-builders-runners:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Test xcode tools install
        run: echo "testing xcode tools install"
      - name: Test homebrew install
        run: echo "testing homebrew install"
      - name: Test docker desktop install
        run: echo "testing docker desktop install"
      - name: Test docker compose build
        run: echo "testing docker compose build"
      - name: Test ansible runner
        run: echo "testing ansible runner"
