name: "Docs: Deploy to GitHub pages"

on:
  push:
    branches: [ main ]

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        directory: "docs/_build"
        github_token: ${{ secrets.GITHUB_TOKEN }}
